image: docker

.template: &template
  stage: build
  before_script:
    - 'apk add curl'
    - 'curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64'
    - 'chmod +x container-structure-test-linux-amd64'
    - 'mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test'
    - 'docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS'
  script:
    - docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg NODE_VERSION=${NODE_VERSION} --build-arg DOCKER_VERSION=${DOCKER_VERSION} --build-arg GIT_LFS_VERSION=${GIT_LFS_VERSION} --build-arg ANSISTRANO_DEPLOY_VERSION=${ANSISTRANO_DEPLOY_VERSION} --build-arg ANSISTRANO_ROLLBACK_VERSION=${ANSISTRANO_ROLLBACK_VERSION} --no-cache -t 1drop/php-${IMAGE_VERSION}-docker-utils .
    - sed -i 's@###PHP_VERSION###@'"$PHP_VERSION"'@' test.yaml
    - sed -i 's@###DOCKER_VERSION###@'"$DOCKER_VERSION"'@' test.yaml
    - sed -i 's@###NODE_VERSION###@'"$NODE_VERSION"'@' test.yaml
    - /usr/local/bin/container-structure-test test --image 1drop/php-${IMAGE_VERSION}-docker-utils --config test.yaml
    - docker push 1drop/php-${IMAGE_VERSION}-docker-utils
    - docker tag 1drop/php-${IMAGE_VERSION}-docker-utils 1drop/php-utils:${PHP_VERSION}
    - docker push 1drop/php-utils:${PHP_VERSION}

# Deprecated (incompatible with PHPStan)
.php70:
  variables:
    IMAGE_VERSION: "70"
    PHP_VERSION: "7.0"
    GIT_LFS_VERSION: "2.7.2"
    DOCKER_VERSION: "18.09.6"
    ANSISTRANO_DEPLOY_VERSION: "1.12.0"
    ANSISTRANO_ROLLBACK_VERSION: "1.5.0"
    NODE_VERSION: "12"
  <<: *template

php71:
  variables:
    IMAGE_VERSION: "71"
    PHP_VERSION: "7.1"
    GIT_LFS_VERSION: "2.7.2"
    DOCKER_VERSION: "18.09.6"
    ANSISTRANO_DEPLOY_VERSION: "1.12.0"
    ANSISTRANO_ROLLBACK_VERSION: "1.5.0"
    NODE_VERSION: "12"
  <<: *template

php72:
  variables:
    IMAGE_VERSION: "72"
    PHP_VERSION: "7.2"
    GIT_LFS_VERSION: "2.7.2"
    DOCKER_VERSION: "18.09.6"
    ANSISTRANO_DEPLOY_VERSION: "1.12.0"
    ANSISTRANO_ROLLBACK_VERSION: "1.5.0"
    NODE_VERSION: "12"
  <<: *template

php73:
  variables:
    IMAGE_VERSION: "73"
    PHP_VERSION: "7.3"
    GIT_LFS_VERSION: "2.7.2"
    DOCKER_VERSION: "18.09.6"
    ANSISTRANO_DEPLOY_VERSION: "1.12.0"
    ANSISTRANO_ROLLBACK_VERSION: "1.5.0"
    NODE_VERSION: "12"
  <<: *template
